/**
 * Created by cristianfelix on 1/14/16.
 */

export default {
    SELECT_ADD_RULE: "SELECT_ADD_RULE",
    SELECT_REMOVE_RULE: "SELECT_REMOVE_RULE",

    SEGMENT_SET_FIELD: "SEGMENT_SET_FIELD",
    SEGMENT_CLEAR: "SEGMENT_CLEAR",
    SEGMENT_MERGE: "SEGMENT_MERGE",
    SEGMENT_SPLIT: "SEGMENT_SPLIT",
    SEGMENT_ADD_EXCLUDE: "SEGMENT_ADD_EXCLUDE",
    SEGMENT_REMOVE_EXCLUDE: "SEGMENT_REMOVE_EXCLUDE",
    SEGMENT_LIMIT: "SEGMENT_LIMIT",
    SEGMENT_SORT: "SEGMENT_SORT",

    SUMMARIZE_ADD_SEGMENT: "SUMMARIZE_ADD_SEGMENT",
    SUMMARIZE_REMOVE_SEGMENT: "SUMMARIZE_ADD_SEGMENT",
    SUMMARIZE_ADD_SUMMARY: "SUMMARIZE_ADD_SUMMARY",
    SUMMARIZE_REMOVE_SUMMARY: "SUMMARIZE_REMOVE_SUMMARY",
    SUMMARIZE_COMBINE_SEGMENTS: "SUMMARIZE_COMBINE_SEGMENTS",

    SUMMARY_ADD_EXCLUDE: "SUMMARY_ADD_EXCLUDE",
    SUMMARY_REMOVE_EXCLUDE: "SUMMARY_ADD_EXCLUDE",
    SUMMARY_SET_SAMPLE: "SUMMARY_SET_SAMPLE",
    SUMMARY_SET_VISUALIZATION: "SUMMARY_SET_VISUALIZATION",
    SUMMARY_SET_AVERAGE_RATING: "SUMMARY_SET_AVERAGE_RATING",
    SUMMARY_ADD_METRIC: "SUMMARY_ADD_METRIC",
    SUMMARY_REMOVE_METRIC: "SUMMARY_REMOVE_METRIC",

    DOCUMENTS_SHOW: "DOCUMENTS_SHOW",
    DOCUMENTS_HIDE: "DOCUMENTS_HIDE"
};